#define T_QMARK                          1
#define T_OR                             2
#define T_AND                            3
#define T_EQ                             4
#define T_NE                             5
#define T_LT                             6
#define T_LE                             7
#define T_GT                             8
#define T_GE                             9
#define T_ADD                           10
#define T_SUB                           11
#define T_MUL                           12
#define T_DIV                           13
#define T_MOD                           14
#define T_NOT                           15
#define T_COLON                         16
#define T_N                             17
#define T_LPAREN                        18
#define T_RPAREN                        19
#define T_NUM                           20
